input: _doxygen/xml
output: docs/modules/ROOT/pages
template:
  index: doxygen2adoc/index.adoc
  nav: doxygen2adoc/nav.adoc

header: doxygen2adoc/header.adoc

partial:
  function: doxygen2adoc/function.adoc

global:
  sourceLanguage: csharp

nav: docs/modules/ROOT/partials/nav.adoc

exclude:
  - file
  - dir
  - namespace
  - page
