input: _doxygen/xml
output: docs/modules/ROOT/pages
template:
  index: doxygen2adoc/index.adoc
  nav: doxygen2adoc/nav.adoc

partial:
  structTitle: doxygen2adoc/structTitle.adoc

global:
  sourceLanguage: csharp

antora: docs/antora.yml

nav: docs/modules/ROOT/partials/nav.adoc

parts:
  methods: ~
  staticMethods: ~

exclude:
  - file
  - dir
  - namespace
  - page
