#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

brew install awscli

brew tap wooga/unityversions

unityversion="${UNITY_VERSION:-5.6.4f1}"

# # Install Unity
if [ ! -f /Applications/Unity-$unityversion/Unity.app/Contents/Pkginfo ]; then
  brew cask install unity@$unityversion
fi

if [ ! -f /Applications/Unity-$unityversion/PlaybackEngines/AndroidPlayer/ivy.xml ]; then
  brew cask install unity-android-support-for-editor@$unityversion
fi

if [ "$(which rvm)" == "" ]; then curl -sSL https://get.rvm.io | bash -s -- --autolibs=read-fail; fi
