#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

brew tap caskroom/cask
brew tap wooga/unityversions


# Install Unity 5
if [ ! -f /Applications/Unity/Unity.app/Contents/Pkginfo ]; then
  brew cask install unity@5.6.4f1
fi

if [ ! -f /Applications/Unity/PlaybackEngines/AndroidPlayer/ivy.xml ]; then
  brew cask install unity-android-support-for-editor@5.6.4f1
fi
