version: 2.1

orbs:
  teak: teak/sdk-utils@0.0.13

jobs:
  build:
    macos:
      xcode: "11.7.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew
            - vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: |
            bundle exec rake
            mkdir build
            mv Teak.unitypackage build/Teak.unitypackage
      - run:
          name: Compute Checksum
          command: |
            shasum -a512 build/Teak.unitypackage > build/Teak.unitypackage.sha512
      - run:
          name: Build UPM Package
          command: |
            UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - upm-package-teak/*
      - run:
          name: ReadTheDocs.org Unified Docs
          command: curl -X POST -d "branches=master" -d "token=$RTD_TOKEN" https://readthedocs.org/api/v2/webhook/teak/41148/

  tag_build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "37:d2:d9:09:bc:0d:c3:41:f4:68:58:79:80:9c:f5:78"
            - "c4:51:dc:a2:59:e6:5a:77:de:7b:c0:55:c8:ac:32:66"
      - teak/tag-promote:
          on_tag: |
            UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:deploy

  deploy_versioned:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/Teak.unitypackage s3://teak-build-artifacts/unity/Teak-$(git describe --tags --always).unitypackage --acl public-read
            aws s3 cp build/Teak.unitypackage.sha512 s3://teak-build-artifacts/unity/Teak-$(git describe --tags --always).unitypackage.sha512 --acl public-read

  deploy_latest:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "37:d2:d9:09:bc:0d:c3:41:f4:68:58:79:80:9c:f5:78"
            - "c4:51:dc:a2:59:e6:5a:77:de:7b:c0:55:c8:ac:32:66"
      - run:
            name: Merge UPM Branch
            command: |
              export PVERSION=`git log -1 --pretty=%B | perl -wne '/[Pp]romote( to)?: ([\w\.\-]+)/i and print $2'`
              UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:merge
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/Teak.unitypackage s3://teak-build-artifacts/unity/Teak.unitypackage --acl public-read
            aws s3 cp build/Teak.unitypackage.sha512 s3://teak-build-artifacts/unity/Teak.unitypackage.sha512 --acl public-read
workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - tag_build:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
