version: 2.1

orbs:
  teak: teak/sdk-utils@1
  buildomat: teak/buildomat@0.1

jobs:
  build:
    macos:
      xcode: "12.5.1"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew
            - vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: |
            bundle exec rake
            mkdir build
            mv Teak.unitypackage build/Teak.unitypackage
      - run:
          name: Compute Checksum
          command: |
            shasum -a512 build/Teak.unitypackage > build/Teak.unitypackage.sha512
      - run:
          name: Build UPM Package
          command: |
            git submodule init && git submodule update --recursive
            UPM_BUILD_TEMP=upm-build bundle exec rake upm:build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - upm-build/*
      - teak/build-antora-playbook:
          build_type: development

  tag_build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - teak/tag-promote

  deploy_versioned:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Deploy UPM to Git Repo
          command: UPM_BUILD_TEMP=upm-build UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:deploy_versioned
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - upm-package-teak/*
      - buildomat/aws-oidc-assume
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/Teak.unitypackage s3://teak-build-artifacts/unity/Teak-$(git describe --tags --always).unitypackage --acl public-read
            aws s3 cp build/Teak.unitypackage.sha512 s3://teak-build-artifacts/unity/Teak-$(git describe --tags --always).unitypackage.sha512 --acl public-read

  deploy_latest:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
            name: Update UPM Branch Heads
            command: |
              UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:deploy_latest
      - buildomat/aws-oidc-assume
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/Teak.unitypackage s3://teak-build-artifacts/unity/Teak.unitypackage --acl public-read
            aws s3 cp build/Teak.unitypackage.sha512 s3://teak-build-artifacts/unity/Teak.unitypackage.sha512 --acl public-read
workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          context:
            - Antora
          filters:
            tags:
              ignore: /.*/
      - tag_build:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

  tagged-build:
    jobs:
      - build:
          context:
            - Antora
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          context:
            - AWS-OIDC-Role
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          context:
            - AWS-OIDC-Role
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
