version: 2.1

orbs:
  teak: teak/sdk-utils@0.0.9

jobs:
  build:
    macos:
      xcode: "11.2.1"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - run:
          name: Check Homebrew Version
          command: |
            echo "Checking for Homebrew version $HOMEBREW_VERSION"
            [ `brew --version | sed -n 1p | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'` = $HOMEBREW_VERSION ] || brew update
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: |
            # gem update bundler # This isn't needed right now, it'll cause an error and 2.0.2 is ok for a version
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - /usr/local/Homebrew/
            - ~/Library/Caches/Homebrew
            - vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - run:
          name: Build Teak SDK
          command: |
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake
            mkdir -p build/$UNITY_VERSION
            mv Teak.unitypackage build/$UNITY_VERSION/Teak.unitypackage
      - run:
          command: |
            mkdir -p /tmp/unity_logs
            cp unity.log /tmp/unity_logs
            bundle exec rake unity:returnlicense
          when: on_fail
      - run:
          name: Build UPM Package
          command: |
            UPM_PACKAGE_REPO=upm-package-teak bundle exec rake upm:build
      - store_artifacts:
          path: /tmp/unity_logs
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - upm-package-teak/*
      - run:
          name: ReadTheDocs.org Unified Docs
          command: curl -X POST -d "branches=master" -d "token=$RTD_TOKEN" https://readthedocs.org/api/v2/webhook/teak/41148/

  tag_build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "32:a9:a0:89:52:f0:29:d6:fa:7c:76:ed:ba:9a:70:17"
            - "c4:51:dc:a2:59:e6:5a:77:de:7b:c0:55:c8:ac:32:66"
      - teak/tag-promote:
          on_tag: (cd upm-package-teak ; git config user.email "team@teak.io" ; git config user.name "Teak CI" ; git checkout -b $PVERSION ; git add -A ; git commit -am "$PVERSION" ; GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_32a9a08952f029d6fa7c76edba9a7017' git push --set-upstream origin $PVERSION)

  deploy_versioned:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/$UNITY_VERSION/Teak.unitypackage s3://teak-build-artifacts/unity/Teak-$(git describe --tags --always).unitypackage --acl public-read
      # - run:
      #     name: Trigger Cleanroom Build
      #     command: bundle exec rake build:cleanroom

  deploy_latest:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp build/$UNITY_VERSION/Teak.unitypackage s3://teak-build-artifacts/unity/Teak.unitypackage --acl public-read
workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - tag_build:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

  tagged-build:
    jobs:
      - build:
          context: unity-5
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          context: unity-5
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          context: unity-5
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
