= Deep Links
:page-pagination:

Deep Linking with Teak is based on routes, which act like URLs. These routes
allow you to specify variables

You can add routes using:

doxygen2adoc:RegisterRoute(string,string,string,Action<Dictionary<string, object>>)[]

.Example
[source]
----
void Awake()
{
    Teak.Instance.RegisterRoute("/store/:sku", "Store", "Open the store to an SKU", (Dictionary<string, object> parameters) => {
        // Any URL query parameters, or path parameters will be contained in the dictionary
        Debug.Log("Open the store to this sku - " + parameters["sku"]);
    });
}
----

IMPORTANT: You need to register your deep link routes before you call `IdentifyUser`.

== How Routes Work

Routes work like URLs where parts of the path can be a variable. In the example
above, the route is `/store/:sku`. Variables in the path are designated with `:`.
So, in the route `/store/:sku` there is a variable named `sku`.

This means that if the deep link used to launch the app was `/store/io.teak.test.dollar`
was used to open the app, it would call the function and assign the value `io.teak.test.dollar`
to the key `sku` in the dictionary that is passed in.

This dictionary will also contain any URL query parameters. For example:

    /store/io.teak.test.dollar?campaign=email

In this link, the value `io.teak.test.dollar` would be assigned to the key `sku`,
and the value `email` would be assigned to the key `campaign`.

// The route system that Teak uses is very flexible, let's look at a slightly more complicated example.

// What if we wanted to make a deep link which opened the game to a specific slot machine.

== When Are Deep Links Executed

Deep links are passed to an application as part of the launch. The Teak SDK holds
onto the deep link information and waits until your app has finished launching,
and initializing.

Deep links will get processed the sooner of:

* Your app calls `IdentifyUser`
* Your app calls `ProcessDeepLinks`

`ProcessDeepLinks` is provided so that you can signify that deep links should be
processed earlier than your call to `IdentifyUser` or so that you can still process
deep links in the case of a user opting out of tracking.


