= Local Notifications

== Scheduling a Local Notification
To schedule a notification from your game, use:

doxygen2adoc:ScheduleNotification(string,string,long,Reply)[]

NOTE: The maximum delay for a Local Notification is 30 days.

== Scheduling a Long-Distance Notification
A notification which is scheduled from code, but delivered to a different player
beside the current player is called a "long distance notification".

doxygen2adoc:ScheduleNotification(string,long,string[],Reply)[]

NOTE: The maximum delay for a Long-Distance Notification is 30 days.

== Canceling a Notification
To cancel a previously scheduled notification, use:

doxygen2adoc:CancelScheduledNotification(string,Reply)[]

== Canceling all Local Notifications

To cancel all previously scheduled local notifications, use:

doxygen2adoc:CancelAllScheduledNotifications(Reply)[]

NOTE: This call is processed asynchronously. If you immediately call
`TeakNotification.ScheduleNotification()` after calling
`TeakNotification.CancelAllScheduledNotifications()` it is possible for your
newly scheduled notification to also be canceled. We recommend waiting until the
callback has fired before scheduling any new notifications.

