= Notification Opt Outs

== Determining if User Has Disabled Push Notifications
You can use Teak to get the state of push notifications for your app.

If notifications are disabled, you can prompt them to re-enable them on the
settings page for the app, and use Teak to go directly the settings for your app.

== Notification State

To get the state of push notifications, use:
[source]
----
NotificationState PushNotificationState
----

.NotificationState Values
[cols="1,2a"]
|===
|Value |Description
|UnableToDetermine |Unable to determine the notification state.

|Enabled |Notifications are enabled, your app can send push notifications.

|Disabled |Notifications are disabled, your app cannot send push notifications.

|Provisional |Provisional notifications are enabled, your app can send notifications but they will only display in the Notification Center (iOS 12+ only).

|NotRequested |The user has not been asked to authorize push notifications (iOS only).
|===

.Example
[source]
----
if (Teak.Instance.PushNotificationState == Teak.NotificationState.Disabled) {
    // Show a button that will let users open the settings
}
----

== Opening the Settings for Your App

If you want to show the settings for your app, use:

doxygen2adoc:OpenSettingsAppToThisAppsSettings()[]

.Example
[source]
----
// ...
// When a user presses a button indicating they want to change their notification settings
Teak.Instance.OpenSettingsAppToThisAppsSettings()
----

