= Teak SDK 5

Teak SDK 5 will be released in late 2024. As the next major version of the SDK, it will remove all methods currently marked as obsolete, and will also introduce changes to Teak's automatic data collection. To aid in the migration from 4.x to 5 the SDK provides a way to opt-in to new SDK 5 behaviors.

== Previewing SDK 5 Behaviors

If you are using *"Build Post-Processing"* simply check the box for *"Enable SDK 5 Behaviors [?]"* in the Teak Settings in Unity. Otherwise,
follow the platform specific directions below.

=== iOS

To enable this, add the ``TeakSDK5Behaviors`` boolean key to your ``Info.plist``, and set it to ``true``.

.Info.plist
[source,xml]
----
  <key>TeakSDK5Behaviors</key>
  <true/>
----

=== Android

To enable this, add the ``io_teak_sdk5_behaviors`` boolean key to your ``AndroidManifest.xml``, and set it to ``true``.

.AndroidManifest.xml
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<manifest>
  <application>
    <meta-data android:name="io_teak_sdk5_behaviors" android:value="true" />
  </application>
</manifest>
----

== SDK 5 Behavior Preview Functionality

- Teak will no longer automatically collect Facebook Access Token, instead you must pass the Facebook User Id to <<Teak.IdentifyUser(string,UserConfiguration)>>
- Teak will no longer automatically collect email addresses from Facebook, instead you must pass the email address to <<Teak.IdentifyUser(string,UserConfiguration)>>
