= Teak Features in Unity
:page-aliases: working-with-unity.adoc


// TODO: Put an intro blurb here.


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Identify User

`identifyUser` is required for Teak to function. See the xref:quickstart/required-code.adoc[Getting Started] guide for the basic setup.

// TODO: Put an identify user section here



// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// == Notifications
// TODO: Put a high level intro to notification types here.


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== User Notification State 

On both iOS and Android >13, it is required that you request permission to send notifiactions to users.

=== Requesting Push Notification Permissions   

.Requesting Push Notification Permissions Using Teak
[source]
----
Teak.Instance.RegisterForNotifications();
----

This method have no effect on non-iOS builds, and is safe to use on iOS 8+.

NOTE: We suggest that you don't simply ask for push permissions when the app starts.
We'll be happy to talk with you to figure out what works best for your title.

You can use Teak to get the state of push notifications for your app.

If notifications are disabled, you can prompt them to re-enable them on the
settings page for the app, and use Teak to go directly the settings for your app.

=== Determine if User Has Disabled Push Notifications 

To get the state of push notifications, use:
[source]
----
NotificationState PushNotificationState
----

.NotificationState Values
[cols="1,2a"]
|===
|Value |Description
|UnableToDetermine |Unable to determine the notification state.

|Enabled |Notifications are enabled, your app can send push notifications.

|Disabled |Notifications are disabled, your app cannot send push notifications.

|Provisional |Provisional notifications are enabled, your app can send notifications but they will only display in the Notification Center (iOS 12+ only).

|NotRequested |The user has not been asked to authorize push notifications (iOS only).
|===

.Example
[source]
----
if (Teak.Instance.PushNotificationState == Teak.NotificationState.Disabled) {
    // Show a button that will let users open the settings
}
----

=== Opening the Settings for Your App 

If you want to show the settings for your app, use:

doxygen2adoc:OpenSettingsAppToThisAppsSettings()[]

.Example
[source]
----
// ...
// When a user presses a button indicating they want to change their notification settings
Teak.Instance.OpenSettingsAppToThisAppsSettings()
----


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Notification Event Listeners
Whenever your game is launched via a push notification, local notification, or email
link Teak will let you know by sending out an event to all listeners.

You can listen for that event during by first writing a listener function.

.Example Notification Listener Function
[source]
----
void MyOnLaunchedFromNotificationListener(TeakNotification notification)
{
    Debug.Log("OnLaunchedFromNotification: " +
        notification.CreativeId + " - " +
        notification.ScheduleId + " Incentivized? " +
        notification.Incentivized);
}
----

And then adding it to the `Teak.Instance.OnLaunchedFromNotification` event during
`Awake()` in any `MonoBehaviour`.

.Adding Example Notification Listener
[source]
----
void Awake()
{
    Teak.Instance.OnLaunchedFromNotification += MyOnLaunchedFromNotificationListener;
}
----

See <<TeakNotification>> for more details.


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Local Notifications 


// TODO: Add a blurb here about what local notifications are and when to use them.


You can use Teak to schedule notifications for the future; delivered either to
the current user, or other users.

NOTE: You get the full benefit of Teak's analytics, A/B testing, and Content Management System when using local notifications!

[IMPORTANT]
====
All notification related methods are coroutines. Unless you want the
method to block execution, you must use `StartCoroutine`.
====

=== Scheduling a Local Notification
To schedule a notification from your game, use:

doxygen2adoc:ScheduleNotification(string,string,long,Reply)[]

NOTE: The maximum delay for a Local Notification is 30 days.

=== Scheduling a Long-Distance Notification
A notification which is scheduled from code, but delivered to a different player
beside the current player is called a "long distance notification".

doxygen2adoc:ScheduleNotification(string,long,string[],Reply)[]

NOTE: The maximum delay for a Long-Distance Notification is 30 days.

=== Canceling a Local Notification
To cancel a previously scheduled notification, use:

doxygen2adoc:CancelScheduledNotification(string,Reply)[]

=== Canceling all Local Notifications

To cancel all previously scheduled local notifications, use:

doxygen2adoc:CancelAllScheduledNotifications(Reply)[]

NOTE: This call is processed asynchronously. If you immediately call
`TeakNotification.ScheduleNotification()` after calling
`TeakNotification.CancelAllScheduledNotifications()` it is possible for your
newly scheduled notification to also be canceled. We recommend waiting until the
callback has fired before scheduling any new notifications.


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Rewards

Whenever your game should grant a reward to a user Teak will let you know by sending
out an event to all listeners.

You can listen for that event during by first writing a listener function, for example:

.Example Reward Listener
[source]
----
void MyRewardListener(TeakReward reward)
{
    switch (reward.Status) {
        case TeakReward.RewardStatus.GrantReward: {
            // The user has been issued this reward by Teak
            foreach(KeyValuePair<string, object> entry in reward.Reward)
            {
                Debug.Log("[Teak Unity Cleanroom] OnReward -- Give the user " +
                    entry.Value + " instances of " + entry.Key);
            }
        }
        break;

        case TeakReward.RewardStatus.SelfClick: {
            // The user has attempted to claim a reward
            // from their own social post
        }
        break;

        case TeakReward.RewardStatus.AlreadyClicked: {
            // The user has already been issued this reward
        }
        break;

        case TeakReward.RewardStatus.TooManyClicks: {
            // The reward has already been claimed its
            // maximum number of times globally
        }
        break;

        case TeakReward.RewardStatus.ExceedMaxClicksForDay: {
            // The user has already claimed their maximum number of rewards
            // of this type for the day
        }
        break;

        case TeakReward.RewardStatus.Expired: {
            // This reward has expired and is no longer valid
        }
        break;

        case TeakReward.RewardStatus.InvalidPost: {
            // Teak does not recognize this reward id
        }
        break;
    }
}
----

And then adding it to the `Teak.Instance.OnReward` event during `Awake()` in any `MonoBehaviour`:

.Adding Listener to OnReward Event
[source]
----
void Awake()
{
    Teak.Instance.OnReward += MyRewardListener;
}
----

See <<TeakReward>> for more details.

// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Deep Links

Deep Linking with Teak is based on routes, which act like URLs. These routes
allow you to specify variables

You can add routes using:

doxygen2adoc:RegisterRoute(string,string,string,Action<Dictionary<string, object>>)[]

.Example
[source]
----
void Awake()
{
    Teak.Instance.RegisterRoute("/store/:sku", "Store", "Open the store to an SKU", (Dictionary<string, object> parameters) => {
        // Any URL query parameters, or path parameters will be contained in the dictionary
        Debug.Log("Open the store to this sku - " + parameters["sku"]);
    });
}
----

IMPORTANT: You need to register your deep link routes before you call `IdentifyUser`.

=== How Routes Work

Routes work like URLs where parts of the path can be a variable. In the example
above, the route is `/store/:sku`. Variables in the path are designated with `:`.
So, in the route `/store/:sku` there is a variable named `sku`.

This means that if the deep link used to launch the app was `/store/io.teak.test.dollar`
was used to open the app, it would call the function and assign the value `io.teak.test.dollar`
to the key `sku` in the dictionary that is passed in.

This dictionary will also contain any URL query parameters. For example:

    /store/io.teak.test.dollar?campaign=email

In this link, the value `io.teak.test.dollar` would be assigned to the key `sku`,
and the value `email` would be assigned to the key `campaign`.

// The route system that Teak uses is very flexible, let's look at a slightly more complicated example.

// What if we wanted to make a deep link which opened the game to a specific slot machine.

=== When Are Deep Links Executed

Deep links are passed to an application as part of the launch. The Teak SDK holds
onto the deep link information and waits until your app has finished launching,
and initializing.

Deep links will get processed the sooner of:

* Your app calls `IdentifyUser`
* Your app calls `ProcessDeepLinks`

`ProcessDeepLinks` is provided so that you can signify that deep links should be
processed earlier than your call to `IdentifyUser` or so that you can still process
deep links in the case of a user opting out of tracking.


// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Post Launch Summary

Each time your game launches, Teak will pass all of the information it has on the launch to you via the ``OnPostLaunchSummary`` event.

See <<TeakPostLaunchSummary>> for more details.

// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Player Properties 

Teak can store up to 16 numeric, and 16 string properties per player. These
properties can then be used for targeting.

You do not need to register the property in the Teak Dashboard prior to sending
them from your game, however you will need to register them in the Teak Dashboard
before using them in targeting.

=== Numeric Property
To set a numeric property, use::

doxygen2adoc:SetNumericAttribute(string,double)[]

.Example
[source]
----
Teak.Instance.SetNumericAttribute("coins", new_coin_balance);
----

=== String Property 

To set a string property, use:

doxygen2adoc:SetNumericAttribute(string,string)[]

.Example
[source]
----
Teak.Instance.SetStringAttribute("last_slot", "amazing_slot_name");
----

// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Analytics Events

Teak can be used to track analytics events which can then be used for targeting. These events are automatically batched by the Teak SDK, you do not need to perform your own batching.

=== Event Format

Teak events are a tuple of values, 'action', 'object type' and 'object instance'.
For example: ['LevelUp', 'Fishing', '13'].

Object instance, and object type are optional, but if you provide an object instance,
you must also provide an object type, for example ['FishCaught', null, '13'] is not allowed, but ['FishCaught', 'Salmon'] is allowed.

=== Tracking an Event

To track that an event occurred, use:

doxygen2adoc:TrackEvent(string,string,string)[]

.Example
[source]
----
Teak.Instance.TrackEvent("LevelUp", "Fishing", "13");
----

=== Incrementing Events

Incremented events are used for analytics which grow over time. You cannot provide negative values.

To increment an event, use:

doxygen2adoc:IncrementEvent(string,string,string,long)[]

.Examples
[source]
----
Teak.Instance.IncrementEvent("coin_sink", "slot", "Happy Land Slots", 25000);
Teak.Instance.IncrementEvent("spin", "slot", "Happy Land Slots", 1);
// <after the spin happens>
Teak.Instance.IncrementEvent("coin_source", "slot", "Happy Land Slots", 1000000);
----

// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Reporting Facebook Payments Purchases 

// TODO: Note auto reporting of payments on iOS and Android. 

If you need to report purchases on Facebook Canvas from using any of the `FB.Canvas.Pay` methods, use:

doxygen2adoc:ReportCanvasPurchase(string)[]

.Example
[source]
----
FB.Canvas.PayWithProductId(
    this.testPurchaseSku,
    "purchaseiap",
    null,
    null,
    (IPayResult result) => {
        if(!string.IsNullOrEmpty(result.Error)) {
            Debug.LogError(result.Error);
        } else {
            Teak.Instance.ReportCanvasPurchase(result.RawResult);
        }
    }
);
----

// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
== Logout 

You can log out the current user using `Logout`. If the user is logged out, Teak
will not process deep links or rewards until a user is logged in, via `IdentifyUser`.
