= Testing Your Teak Installation
:toc:

Testing SDK integrations in Unity can be a little tricky. Teak can't talk to Teak's servers from inside the Unity Editor. But there are a few things we can do to make sure things are installed correctly.

* If the Teak package is successfully installed and called, you will see the following message in the console.  \


----
[Teak] Unity SDK Version: 4.1.14
----

* We can turn on additional debug logging with `Trace.` Add this before your IdentifyUser call. \


[source, csharp]
----
Teak.Instance.Trace = true;
----

* With Trace turned on, you will see logging for additional function calls, such as the following.

----
[Teak] IdentifyUser(): the_unique_player_id
----

You'll find more logging options in https://docs.teak.io/unity/latest/debugging.html[Debugging Your Code with Teak] that will help as you build more Teak functionality into your game. But before that, it's time to get your game built and running on a test device, and see your player in the Teak dashboard.


