= Before You Start

It would be frustrating to start integrating the Teak SDK, only to find out you
don't have credentials to test the push notifications, so before you start here's
what you need to make things go smoothly.

[IMPORTANT]
.Android Target SDK Version
====
Please note that Teak SDK 4.0.0 supports a maximum `targetSdkVersion` of 30.
Teak SDK 4.1.0 and greater supports `targetSdkVersion` of 31. Teak SDK 4.2.0
supports `targetSdkVersion` of 33.
====

[IMPORTANT]
.Unity Mobile Notifications Plugin
====
The Unity Mobile Notifications Plugin cannot be used alongside Teak.
====

== iOS
In order to send push notifications to your game on iOS, Teak needs your
Apple Push Notification Service (APNS) Certificates.

You will need an Administrator on your Apple Developer account for this step,
and the will need to use a Mac in order to perform this step.

Follow these instructions to create your APNS certificates and provide them to Teak (xref:usage:reference:page$apple-apns.adoc[Creating and Uploading your Apple Push Notification Service (APNS) Certificates, window=_blank]).

== Android
In order to send push notifications to your game on Android, Teak needs the
Server Key and Sender ID from your Firebase project.

You will need Editor or Owner role on the Firebase project in order to view/create
server keys for Cloud Messaging.

Follow these instructions to get your Server Key and Sender ID (xref:usage:reference:page$firebase-gcm.adoc[Finding your Android Push Credentials on Firebase, window=_blank]).
