= Getting Started with Teak in Unity
:page-aliases: ../before-you-start.adoc
:page-pagination:

Welcome to the getting started guide for Teak in Unity.

In this guide, we will walk you through the process of setting up Teak in your Unity game. By the end of this guide you will be able to send a push notification to your Android or iOS device.

This guide assumes your game is cross platform, and has instructions for both iOS and Android. Skip the sections you don't need.

== Requirements

Before we begin, ensure that you have the following prerequisites in place to ensure a smooth integration:

=== Unity Requirements
* [x] Unity 2020 or newer

=== iOS Requirements
* [x] An https://developer.apple.com/[Apple Developer, window=_blank] account with administrator permissions.
* [x] A Mac with https://developer.apple.com/xcode/[XCode, window=_blank] installed.

=== Android Requirements
* [x] A https://firebase.google.com/[Firebase project] with an Editor or Owner role.
* [x] https://firebase.google.com/docs/unity/setup[Firebase Unity SDK, window=_blank] installed.
* [x] External Dependency Manager for Unity (Installed with Firebase)

NOTE: If your game already includes any Firebase product from a .unitypackage, it should be compatible with Teak. However, if you don't have any Firebase products installed yet, we suggest installing only the **FirebaseMessaging.unitypackage** to ensure compatibility with Teak.

NOTE: Teak SDK 4.3.0 supports a maximum `targetSdkVersion` of 34. +
Teak SDK 4.2.0 supports a maximum `targetSdkVersion` of 33. +
Teak SDK 4.1.0 supports a maximum `targetSdkVersion` of 31. +
Teak SDK 4.0.0 supports a maximum `targetSdkVersion` of 30.

With the requirements out of the way, let's get started.

First, we'll set up your Teak dashboard.
