= Add Required Code
:page-pagination:

It's time to tell Teak about your players so you can start logging sessions and gathering metrics.

== Identify User

This is where we tell Teak how to identify the current user.

==== What Player ID should we use?

We assume your game uses a user ID to store progress, coin balances, and other useful data. For the sanity of your analytics team, you send us that ID and we'll use it too.

* [*] It should be uniquely identify the current user.
* [*] Ideally the same ID that is used in your game's backend.
* [*] Send it as early as possible in the game's lifecycle.

=== Send your player IDs to Teak

Let's tell Teak about our players using `<<Teak.IdentifyUser(string,UserConfiguration)>>`.

In our game script, as soon as we know the id for our current player, we'll add our call.

.Example
[source,cs]
----
// ...
Teak.UserConfiguration userConfiguration = new Teak.UserConfiguration {};
Teak.Instance.IdentifyUser(YOUR_USER_ID, userConfiguration);
----

<1> We create an empty `userConfiguration` object for now. We'll add data to that in the next step.

<2> Your `YOUR_USER_ID` string must be unique to the player. Again, we highly recommend using the same user id you use in your game's backend.

This is enough to begin tracking and reporting of a session and tracking a daily active user.


=== Sending Additional Data

Next we'll add some data to our `<<Teak.UserConfiguration>>[Farts]`.

NOTE: In SDK 5, Teak will no longer automatically collect Facebook Access Tokens or Emails from Facebook, instead you must pass the Facebook User Id in the `UserConfiguration`.

Here's how we would add an email address and their Facebook ID. This will enable sending emails and templating personalization into our notification and email content.

.Data Example
[source,cs]
----
// ...
Teak.UserConfiguration userConfiguration = new Teak.UserConfiguration {
  Email = YOUR_USER_EMAIL,
  FacebookId = YOUR_USER_FACEBOOK_ID
};
Teak.Instance.IdentifyUser(YOUR_PLAYER_ID, userConfiguration);
----

* Null and empty strings will be ignored.
* If you want to update player data during a session, call `IdentifyUser` again with the new data.
* You can also use `UserConfiguration` to opt-out of some types of data collection.


=== Opting Out of Tracking

If the user has opted out of data collection completely, do not call `IdentifyUser`,
and Teak will not track the user at all.

If the user has opted out of specific data collection, set the corresponding
opt-out to `true` in the `UserConfiguration`.

See the <<Teak.UserConfiguration>>[UserConfiguration Docs] for the available options.


== Ask the Player for Push Permissions

On iOS and Android 13 and greater you are required to ask the user if you can send them notifications. Do that with the `<<RegisterForNotifications()>>` call.

Ideally, you would ask for these permissions at a time that makes sense for your game. In the long term, you can increase your notification opt-in rates by being strategic about when you ask for permission.

But for the purpose of getting up and running fast, let's just put the permissions request right here at game launch.

[source,cs]
----
// ...
Teak.Instance.RegisterForNotifications();
----

Now your game will ask for push permissions when you launch the game. Make sure to approve them on your test device, so that we can send our notification at the end of this tutorial.


== Testing Your Teak Installation

If the Teak package is successfully installed and called, you will see the following message in the console.

----
[Teak] Unity SDK Version: 4.2.1
[Teak] IdentifyUser(): YOUR_PLAYER_ID
----

You'll find more logging options in https://docs.teak.io/unity/latest/debugging.html[Troubleshooting] that will help as you build more Teak functionality into your game. But before that, it's time to build your game and get it running on a test device, so we can see your player in the Teak dashboard.


