= Identify User
:page-pagination:

It's time to tell Teak about your players so you can start logging sessions, gathering metrics, and sending rewards. The first step is to identify a player.

We assume your game uses a player ID to store progress, coin balances, and other useful data. All Teak needs is that ID; it doesn't require full user authentication, just a way to uniquely identify players or devices.


== Use your game's Player ID

Teak requires only a player ID from your game, ideally matching the ID used in your game's backend. By using the same ID that you use in the backend

Initialize the Teak connection early in your game's lifecycle where player identification occurs to ensure complete session logging.


== Add Teak to your game script

If you authenticate users, send the player ID to Teak in your authentication handler method.

* First, add Teak to the ‘using' declarations & MonoBehaviour properties in the appropriate game script:

[source, csharp]
----
//…
using static Teak;
----

Teak is now available for use in this file.

The https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static[`static` keyword] imports Teak as its own type, which means that you will call Teak's own `Instance` property directly.


== Send your player IDs to Teak

Now let's send the first piece of player data to Teak!

* Create a method that calls https://docs.teak.io/unity/latest/api/classTeak.html#classTeak_1aea6260058a77c4d85d7c031cb4e2e68b[Teak.IdentifyUser()]:

[source, csharp]
----
public void identifyTeakUser(string userIdentifier)
{
  UserConfiguration userConfiguration = new UserConfiguration {
    Email = EmailInput.text
  };
  Teak.Instance.IdentifyUser(userIdentifier, userConfiguration);
}
----

This method has two parameters. The first is a `userIdentifier` string, which must be unique to the player—and again, we highly recommend using the same string you use elsewhere in your application. This argument is required.

The second parameter, https://docs.teak.io/unity/latest/api/classTeak_1_1UserConfiguration.html[UserConfiguration], is optional. If you don't define a `userConfiguration`, Teak will create an empty object for this user, which you can update later. The example above shows how you might pass in a form input for a user email address. You can also use UserConfiguration to keep track of a user's Facebook ID or privacy settings.

* Then call your Teak user method when a user is successfully identified by your backend:

[source, csharp]
----
private void handleSuccessfulIdentification(string playerID)
{
  //code executed when player ID is confirmed by your backend
  identifyTeakUser(playerID);
}
----

As discussed above, you likely already have a handler method that is called when a user is first identified. Because you want Teak to track a complete user session, identifying a user for Teak in the handler method gets that data recorded as early as possible in the player journey.


== Ask the Player for Permission

On iOS and Android 13 and greater you are required to ask the user if you can send them notifications. Do that with the RegisterForNotifications call.

Ideally, you would ask for these permissions at a time that makes sense for your game. In the long term, you can increase your notification opt-in rates by being strategic about when you ask for permission.

But for the purpose of getting up and running fast, let's just put the permissions request right here at game launch. \

[source, csharp]
----
private void handleSuccessfulIdentification(string playerID)
{
  //code executed when player ID is confirmed by your backend
  identifyTeakUser(userIdentifier);
  Teak.Instance.RegisterForNotifications();
}
----

Now your game will ask for push permissions when you launch the game. Make sure to approve them on your test device, so that we can send our notification at the end of this tutorial.


== Testing Your Teak Installation

If the Teak package is successfully installed and called, you will see the following message in the console.

----
[Teak] Unity SDK Version: 4.1.14
[Teak] IdentifyUser(): the_unique_player_id
----

You'll find more logging options in https://docs.teak.io/unity/latest/debugging.html[Troubleshooting] that will help as you build more Teak functionality into your game. But before that, it's time to get your game built and running on a test device, and see your player in the Teak dashboard.


